language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
env:
  - BOP_UndyFinish=1 #normal behavior
  - BOP_UndyFinish=0 #force PPR tasks to finish
matrix:
  fast_finish: true
  allow_failures:
  - os: osx #mac is unstable for the time being
  - env: BOP_UndyFinish=0
  exclude: #gcc/osx causes issues
  - os: osx
    env: BOP_UndyFinish=0
#dependencies for the ruby language

sudo: false
addons:
  apt:
    packages:
    - gcc
    - clang
before_install:
  - "if [[ $TRAVIS_OS_NAME = 'linux' ]]; then JOBS='-j'; fi"
  - "if [[ $TRAVIS_OS_NAME = 'osx' ]]; then brew install autoconf openssl; fi"
  - "if [[ $TRAVIS_OS_NAME = 'osx' ]]; then OPENSSL_FLAG=\"--with-openssl-dir=`brew --prefix openssl`\"; fi"
  - "if [[ $TRAVIS_OS_NAME = 'osx' && $CC = 'gcc' ]]; then CC='gcc-4.9'; fi"

install:
  - rake #actual build


before_script: #before tests run
  - "if [[ $TRAVIS_OS_NAME = 'osx' ]]; then rm -f ~/Library/Logs/DiagnosticReports/ruby_*.crash; fi"

#test script
script:
  - rake test
