language: c
compiler:
  - gcc
  - clang
os:
  - linux
#  - osx Disable OSX buids on master until the issues are resolved
#dependencies for the ruby language
sudo: false #remove for OSX or makesure autoconf & openssl are installed
addons:
  apt:
    packages:
    - gcc
    - clang
before_install:
  - "if [[ $TRAVIS_OS_NAME = 'linux' ]]; then JOBS='-j'; fi"
  - "if [[ $TRAVIS_OS_NAME = 'osx' ]]; then brew install autoconf openssl; fi"
  - "if [[ $TRAVIS_OS_NAME = 'osx' ]]; then OPENSSL_FLAG=\"--with-openssl-dir=`brew --prefix openssl`\"; fi"
  - "if [[ $TRAVIS_OS_NAME = 'osx' && $CC = 'gcc' ]]; then CC='gcc-4.9'; fi"

install:
  - "if [[ $TRAVIS_OS_NAME = 'linux' ]]; then sudo apt-get -qq build-dep ruby1.9.1 2>/dev/null; fi"
  - rake #actual build


before_script: #before tests run
  - "if [[ $TRAVIS_OS_NAME = 'osx' ]]; then rm -f ~/Library/Logs/DiagnosticReports/ruby_*.crash; fi"

#test script
script:
  - rake test
