language: c
compiler:
  - gcc
  - clang
os:
  - linux
  #- osx
env:
  - BOP_GroupSize=2
  - BOP_GroupSize=4 #normal understudy, more PPR tasks
matrix:
  fast_finish: true
#dependencies for the ruby language
exclude:
  - os: osx
    env: BOP_UndyFinish=0 BOP_GroupSize=4

sudo: false
addons:
  apt:
    packages:
    - gcc
    - clang
before_install:
  - "if [[ $TRAVIS_OS_NAME = 'linux' ]]; then JOBS='-j'; fi"
  - "if [[ $TRAVIS_OS_NAME = 'osx' ]]; then brew install autoconf openssl; fi"
  - "if [[ $TRAVIS_OS_NAME = 'osx' ]]; then OPENSSL_FLAG=\"--with-openssl-dir=`brew --prefix openssl`\"; fi"
  - "if [[ $TRAVIS_OS_NAME = 'osx' && $CC = 'gcc' ]]; then CC='gcc-4.9'; fi"

install:
  - rake #actual build


before_script: #before tests run
  - "if [[ $TRAVIS_OS_NAME = 'osx' ]]; then rm -f ~/Library/Logs/DiagnosticReports/ruby_*.crash; fi"

#test script
script:
  - rake bop_test
  - rake ruby_test_run
